name: Deploy
on: 
    workflow_run: 
        workflows: build
        types: completed
jobs: 
    Build-and-push-images:
        runs-on: ubuntu-latest
        environment: PROD
        steps: 
            - name: Downloading the artifacts
              uses: dawidd6/action-download-artifact@v2
              with:
                run_id: ${{ github.event.workflow_run.id }}
               # name: ${{ github.event.workflow_run.event.inputs.ARTIFACT_NAME }}
                path: ./artifacts
                search_artifacts: true
            - run: |
                 ls
                 cd */
                 pwd
                 ls
                 cd */
            - name: Build & push Docker image
              uses: mr-smithers-excellent/docker-build-push@v5
              with:
                image: pradeep0877/spring -sample-webapp
                tags: ${{github.run_number}}
                registry: docker.io
                dockerfile: Dockerfile
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
