name: build
on: workflow_dispatch
jobs: 
    Build: 
        runs-on: ubuntu-latest
        steps: 
            - name: Getting our code
              uses: actions/checkout@v3
            - name: cache m2 repo
              uses: actions/cache@v3
              with: 
                path: ~/.m2
                key: key=${{hashFiles('**/pom.xml')}}
                restore-keys: key=${{hashFiles('**/pom.xml')}}
            - name: setting up java 11
              uses: actions/setup-java@v3
              with: 
                java-version: 11
                distribution: 'zulu'
            - name: Building our application
              run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests -Dsonar.projectKey=Pradeep-0877_Spring-Boot-Sample-Project
            - run: ls
            - name: archiving the artifacts
              uses: actions/upload-artifact@v3
              with: 
                name: my-artifact
                path: target/*.jar

            #   mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Pradeep-0877_Spring-Boot-Sample-Project