name: build
on: workflow_dispatch
jobs: 
    Build: 
        runs-on: ubuntu-latest
        steps: 
            - name: Getting our code
              uses: actions/checkout@v3
            - name: setting up java 11
              uses: actions/setup-java@v3
              with: 
                java-version: 11
                distribution: 'zulu'
            - name: Building our application
              run: mvn package